name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Update to the latest version

      - name: Set up JDK
        uses: actions/setup-java@v4  # Update to the latest version
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Build with Maven
        run: mvn clean install
